### ISSUE TITLE
cannot find name for group ID 1000

### ISSUE THREAD

**Issue by shapr** [brimstone/docker-ionic#2]
after using the eval command, trying to run ionic directly from the command line gives this error:

> ionic 
> groups: cannot find name for group ID 1000
> I have no name!@46a3121378ca:/$ 

Is this expected behavior?

**Comment by brimstone** [comment]
I believe so. I don't know of a way to hide these errors. Ionic is mostly used via a command directly, not getting a shell inside the container.

**Comment by shapr** [comment]
ok, thanks for the feedback
